name: Package
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Build package
        run: |
          python -m pip install build twine check-wheel-contents
          python -m build --sdist --wheel .
          ls -l dist
          check-wheel-contents dist/*.whl
      - name: "Check long_description"
        run: "python -m twine check dist/*"
